name: "Analysis"

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    analysis:
        runs-on: ubuntu-latest
        steps:
            -   name: Setup variables
                id: get-vars
                run: |
                    if [ -z "$GITHUB_HEAD_REF" ]; then
                        # push
                        echo "::set-output name=branch::$GITHUB_REF_NAME"
                        echo "::set-output name=pr::$GITHUB_RUN_ID"
                    else
                        # pull request
                        echo "::set-output name=branch::$GITHUB_HEAD_REF"
                        echo "::set-output name=pr::${{ github.event.pull_request.number }}"
                    fi
            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  repository: ${{ steps.get-vars.outputs.repo }}
                  ref: ${{ steps.get-vars.outputs.branch }}
            - name: Set up JDK 17
              uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
              with:
                  distribution: "temurin"
                  java-version: 17
            -   name: Run analysis wrapper
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    scripts/analysis/analysis-wrapper.sh ${{ secrets.GIT_USERNAME }} ${{ secrets.GITHUB_TOKEN }} ${{ steps.get-vars.outputs.branch }} ${{ secrets.LOG_USERNAME }} ${{ secrets.LOG_PASSWORD }} $GITHUB_RUN_NUMBER ${{ steps.get-vars.outputs.pr }}
