# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2023 Andy Scherzinger <info@andy-scherzinger.de>
# SPDX-FileCopyrightText: 2022 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-FileCopyrightText: 2022 Álvaro Brey <alvaro@alvarobrey.com>
# SPDX-License-Identifier: MIT

name: Assemble

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    assemble:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
            - name: Set up JDK 17
              uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
              with:
                  distribution: "temurin"
                  java-version: 17
            -   name: Setup JVM options
                run: |
                    mkdir -p "$HOME/.gradle"
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > "$HOME/.gradle/gradle.properties"
            -   name: Assemble
                uses: gradle/gradle-build-action@v3
                with:
                    arguments: assemble
