name: Check

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, spotlessKotlinCheck, lint ]
        steps:
            - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
            - name: Set up JDK 11
              uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
              with:
                  distribution: "temurin"
                  java-version: 11
            -   name: Setup JVM options
                run: |
                    mkdir -p "$HOME/.gradle"
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > "$HOME/.gradle/gradle.properties"
            -   name: Check ${{ matrix.task }}
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: ${{ matrix.task }}
            -   uses: actions/upload-artifact@v3
                if: ${{ always() }}
                with:
                    name: ${{ matrix.task }}-report
                    path: library/build/reports
