# SPDX-FileCopyrightText: 2017-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2017 Tobias Kaminsky <tobias@kaminsky.me>
# SPDX-License-Identifier: GPL-3.0-or-later
name: Check

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, spotlessKotlinCheck, lint ]
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Set up JDK 17
              uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
              with:
                  distribution: "temurin"
                  java-version: 17
            -   name: Setup JVM options
                run: |
                    mkdir -p "$HOME/.gradle"
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > "$HOME/.gradle/gradle.properties"
            -   name: Check ${{ matrix.task }}
                uses: gradle/gradle-build-action@v3
                with:
                    arguments: ${{ matrix.task }}
            -   uses: actions/upload-artifact@v4
                if: ${{ always() }}
                with:
                    name: ${{ matrix.task }}-report
                    path: library/build/reports
