name: Check

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, spotlessKotlinCheck, lint ]
        steps:
            - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
            - name: Set up JDK 17
              uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
              with:
                  distribution: "temurin"
                  java-version: 17
            -   name: Setup JVM options
                run: |
                    mkdir -p "$HOME/.gradle"
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > "$HOME/.gradle/gradle.properties"
            -   name: Check ${{ matrix.task }}
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: ${{ matrix.task }}
            -   uses: actions/upload-artifact@v3
                if: ${{ always() }}
                with:
                    name: ${{ matrix.task }}-report
                    path: library/build/reports
