name: "Detect snapshot"

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

jobs:
    detekt:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
            - name: Detect SNAPSHOT
              run: scripts/analysis/detectSNAPSHOT.sh
