name: "Detect snapshot"

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

jobs:
    detekt:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
            - name: Detect SNAPSHOT
              run: scripts/analysis/detectSNAPSHOT.sh
